baseURL: ""  # You can set this to your GitHub Pages URL later
languageCode: "en-us"
title: ""  # You can set your title here
theme: "your-theme-name"  # Replace with your current theme

# Hugo Markdown settings (theme-related)
markup:
  goldmark:
    renderer:
      unsafe: true  # Keeps raw HTML rendering in Markdown enabled

# Essential Hugo build settings (theme-related)
disableKinds:
  - taxonomy
  - taxonomyTerm
  - RSS
  - sitemap

# Theme-related params (you can add more as per the theme documentation)
params:
  # Add theme-specific configurations here
  # For example, these could be theme-specific settings for layout, style, etc.

